// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcw8RCyyc1Kvc7b4SDvdA2RGBWhtlaU28',
    appId: '1:251324704090:web:2bdb464c83d5cc96147f63',
    messagingSenderId: '251324704090',
    projectId: 'medreminder-7aa68',
    authDomain: 'medreminder-7aa68.firebaseapp.com',
    databaseURL: 'https://medreminder-7aa68-default-rtdb.firebaseio.com',
    storageBucket: 'medreminder-7aa68.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCey7a33svYMAvKXAZBCg73fPQ69uJlwWs',
    appId: '1:251324704090:android:846a40c79a6b5604147f63',
    messagingSenderId: '251324704090',
    projectId: 'medreminder-7aa68',
    databaseURL: 'https://medreminder-7aa68-default-rtdb.firebaseio.com',
    storageBucket: 'medreminder-7aa68.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcw8RCyyc1Kvc7b4SDvdA2RGBWhtlaU28',
    appId: '1:251324704090:web:f6818927f6307c0c147f63',
    messagingSenderId: '251324704090',
    projectId: 'medreminder-7aa68',
    authDomain: 'medreminder-7aa68.firebaseapp.com',
    databaseURL: 'https://medreminder-7aa68-default-rtdb.firebaseio.com',
    storageBucket: 'medreminder-7aa68.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGdojz5XYwYD7yO-BT1-1L8x8f8_2SMYk',
    appId: '1:251324704090:ios:a4b6c6576885080e147f63',
    messagingSenderId: '251324704090',
    projectId: 'medreminder-7aa68',
    databaseURL: 'https://medreminder-7aa68-default-rtdb.firebaseio.com',
    storageBucket: 'medreminder-7aa68.firebasestorage.app',
    iosClientId: '251324704090-73o8d3jemnl6c269ifuvphp5r5lrd4qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.thirdly',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGdojz5XYwYD7yO-BT1-1L8x8f8_2SMYk',
    appId: '1:251324704090:ios:a4b6c6576885080e147f63',
    messagingSenderId: '251324704090',
    projectId: 'medreminder-7aa68',
    databaseURL: 'https://medreminder-7aa68-default-rtdb.firebaseio.com',
    storageBucket: 'medreminder-7aa68.firebasestorage.app',
    iosClientId: '251324704090-73o8d3jemnl6c269ifuvphp5r5lrd4qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.thirdly',
  );
}
